"""add_task_timings

Revision ID: e269b8eda381
Revises: 711e1becfddc
Create Date: 2026-07-13 22:05:12.456890

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e269b8eda381"
down_revision: str | Sequence[str] | None = "711e1becfddc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("briefs", sa.Column("started_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("briefs", sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("briefs", "finished_at")
    op.drop_column("briefs", "started_at")
    # ### end Alembic commands ###
