/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint to verify backend service status.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/briefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decode Brief
         * @description Creates a brief decoding run and triggers the analysis in the background.
         */
        post: operations["decode_brief_api_v1_briefs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/briefs/{brief_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Brief
         * @description Gets the details and analysis results of a specific brief.
         */
        get: operations["get_brief_api_v1_briefs__brief_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BriefAnalysisResponse
         * @description The structured output format returned by the AI provider.
         */
        BriefAnalysisResponse: {
            /**
             * Project Type
             * @description Main type or domain of the project
             */
            project_type: string;
            /**
             * Budget Info
             * @description Budget description, limits, or constraints mentioned in the brief
             */
            budget_info?: string | null;
            /**
             * Deadline Info
             * @description Deadline, milestones, or timeline constraints mentioned in the brief
             */
            deadline_info?: string | null;
            /**
             * Key Requirements
             * @description List of key requirements extracted from the brief
             */
            key_requirements?: string[];
            /**
             * Risks
             * @description List of identified risks with their severity and mitigation strategies
             */
            risks?: components["schemas"]["RiskItem"][];
        };
        /**
         * BriefRequest
         * @description Input payload for a brief analysis request.
         */
        BriefRequest: {
            /**
             * Text
             * @description Raw brief text to analyze
             * @example We need a mobile app for food delivery. Budget is 15k USD. Deadline: 3 months.
             */
            text: string;
        };
        /**
         * BriefResponse
         * @description Output details of a brief analysis.
         */
        BriefResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["BriefStatus"];
            /** Input Text */
            input_text: string;
            structured_result?: components["schemas"]["BriefAnalysisResponse"] | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * BriefStatus
         * @enum {string}
         */
        BriefStatus: "pending" | "processing" | "completed" | "failed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthCheckState */
        HealthCheckState: {
            /**
             * Status
             * @constant
             */
            Status: "Ok";
        };
        /** RiskItem */
        RiskItem: {
            /**
             * Description
             * @description Description of the identified risk
             */
            description: string;
            /** @description Severity level of the risk */
            severity: components["schemas"]["SeverityEnum"];
            /**
             * Mitigation
             * @description Suggested way to mitigate or minimize the risk
             */
            mitigation: string;
        };
        /**
         * SeverityEnum
         * @enum {string}
         */
        SeverityEnum: "low" | "medium" | "high";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckState"];
                };
            };
        };
    };
    decode_brief_api_v1_briefs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BriefRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_brief_api_v1_briefs__brief_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brief_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
